---
title: "Step-by-step"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Step-by-step}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, echo=FALSE}
library(mbbe)
library(ggplot2) 

a <- data.frame(vals=rnorm(100))
plot <- ggplot2::ggplot(data = a, aes(x = vals)) +
ggplot2::geom_histogram()

```

###  First you need model(s)

Five models are provided with the MBBE package. These models were selected using [pyDarwin](https://certara.github.io/pyDarwin/html/index.html)

equation inline

$a = sin( b/5)$

------------------------------------------------------------------------

link to url chankges color by default

[CNN](http://www.cnn.com)

image - put double space before link to put it on a new line

bulletes:

-   first level

-   2nd level

numbered

1.  first

2.  second

```{r, echo=FALSE}

```

| Col1 | Col2 | Col3 |
|------|------|------|
| 1    | 76   | 3    |
| 1    | 3    | 3    |
| 2    | 4    | 4    |

```{r, echo=FALSE, fig.align="center", fig.cap="test figure"}
print(a$val[1:10])
print(plot)
```
